apiVersion: v1
kind: ConfigMap
metadata:
  name: azmlsi-db-config
data:
  db-keyspace: az_ml_si_keyspace
  db-persona-table: persona_table
  db-persona-edge-table: persona_edge_table
  db-raw-image-table: raw_image_table
  db-refined-image-table: refined_image_table
  db-log-table: log_table
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azmlsi-bs-config
data:
  blob-storage-con: test-data-con
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azmlsi-input-dpmt
  labels:
    app: azmlsi-input-dpmt
spec:
  completions : 1
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: azmlsi-input-dpmt
    spec:
      containers:
      - name: azmlsi-input
        image: azmlsiacr.azurecr.io/input-service
        tty: true
        env:
        - name: BS_TEST_CON
          valueFrom:
            configMapKeyRef:
              name: azmlsi-bs-config
              key: blob-storage-con
        - name: DB_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-keyspace
        - name: DB_PERSONA_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-persona-table
        - name: DB_PERSONA_EDGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-persona-edge-table
        - name: DB_RAW_IMAGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-raw-image-table
        - name: DB_REFINED_IMAGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-refined-image-table
        ports:
        - containerPort: 10350
          name: azure-cosmo-db
        - containerPort: 80
          name: azure-file-str
        volumeMounts:
        - name: bs-secrets
          mountPath: /tmp/secrets/bs
          readOnly: true
        - name: db-secrets
          mountPath: /tmp/secrets/db
          readOnly: true
      restartPolicy: Never
      imagePullSecrets:
      - name: image-pull-secrets
      volumes:
      - name: bs-secrets
        secret:
          secretName: bs-secrets
      - name: db-secrets
        secret:
          secretName: db-secrets
---
kind: Service
apiVersion: v1
metadata:
  name: azmlsi-input-svc
spec:
  selector:
    app: azmlsi-input-dpmt
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: azure-file-str
  - protocol: TCP
    port: 10350
    targetPort: 10350
    name: azure-cosmos-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azmlsi-visualization-deployment
  labels:
    app: azmlsi-visualization-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azmlsi-visualization-deployment
  template:
    metadata:
      labels:
        app: azmlsi-visualization-deployment
    spec:
      containers:
      - name: visualization
        image: azmlsiacr.azurecr.io/viz-service
        imagePullPolicy: Always
        tty: true
        env:
        - name: DB_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-keyspace
        - name: DB_PERSONA_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-persona-table
        - name: DB_PERSONA_EDGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-persona-edge-table
        - name: DB_RAW_IMAGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-raw-image-table
        - name: DB_REFINED_IMAGE_TABLE
          valueFrom:
            configMapKeyRef:
              name: azmlsi-db-config
              key: db-refined-image-table
        ports:
        - containerPort: 5000
        - containerPort: 10350
        volumeMounts:
        - name: db-secrets
          mountPath: /tmp/secrets/db
          readOnly: true
      imagePullSecrets:
      - name: image-pull-secrets
      volumes:
      - name: db-secrets
        secret:
          secretName: db-secrets
---
kind: Service
apiVersion: v1
metadata:
  name: azmlsi-visualization-service
spec:
  selector:
    app: azmlsi-visualization-deployment
  ports:
  - protocol: TCP
    name: web
    port: 5000
    targetPort: 5000
    nodePort: 30080
  - protocol: TCP
    name: cassandra
    port: 10350
    targetPort: 10350
  type: LoadBalancer
